name: Deploy to AWS

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Install Production Dependencies in Dist
      run: |
        cp package.json package-lock.json dist/
        cd dist
        npm ci --omit=dev

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="db_host=${{ secrets.DB_HOST }}" -var="db_user=${{ secrets.DB_USER }}" -var="db_password=${{ secrets.DB_PASSWORD }}" -var="db_name=${{ secrets.DB_NAME }}" -var="db_port=${{ secrets.DB_PORT }}" -var="jwt_secret=${{ secrets.JWT_SECRET }}" -var="environment=${{ vars.ENVIRONMENT }}"

    - name: Terraform Apply
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging') && github.event_name == 'push'
      run: terraform apply -auto-approve -var="db_host=${{ secrets.DB_HOST }}" -var="db_user=${{ secrets.DB_USER }}" -var="db_password=${{ secrets.DB_PASSWORD }}" -var="db_name=${{ secrets.DB_NAME }}" -var="db_port=${{ secrets.DB_PORT }}" -var="jwt_secret=${{ secrets.JWT_SECRET }}" -var="environment=${{ vars.ENVIRONMENT }}"